
<!-- Page Content -->
<div class="container">

  <!-- Portfolio Item Heading -->
  <h1 class="my-4">IMAGENEOLOGIA
    <small>Imagenes Diagnosticas</small>
  </h1>

  <!-- Portfolio Item Row -->
  <div class="row">

    <div class="col-md-8">
      <img class="img-fluid" src= "<?php echo base_url()?>assets/img/tac.jpg" alt="">
    </div>

    <div class="col-md-4">
      <h3 class="my-3">Equipo y tecnología</h3>
      <p>Contamos con personal experto y calificado para asesorar la construcción y el blindaje de las áreas de rayos X, así como la adecuación de la infraestructura hospitalaria para implementar un departamento de imagenología.</p>
      <h3 class="my-3">Imagenes Diagnosticas</h3>
      <ul>
        <li>Rayos X</li>
        <li>Mamografia</li>
        <li>Tomografia</li>
        <li>Resonancia</li>
      </ul>
    </div>

  </div>
  <!-- /.row -->

  <!-- Related Projects Row -->
  <h3 class="my-4">NUESTRAS LINEAS DE TRABAJO</h3>

  <div class="row">

    <div class="col-md-3 col-sm-6 mb-4">
      <a href="#">
            <img class="img-fluid" src="<?php echo base_url()?>assets/img/rx.jpg" alt="">
          </a>
    </div>

    <div class="col-md-3 col-sm-6 mb-4">
      <a href="#">
            <img class="img-fluid" src="<?php echo base_url()?>assets/img/mamografo.jpg" alt="">
          </a>
    </div>

    <div class="col-md-3 col-sm-6 mb-4">
      <a href="#">
            <img class="img-fluid" src="<?php echo base_url()?>assets/img/rxportatil.jpg" alt="">
          </a>
    </div>

    <div class="col-md-3 col-sm-6 mb-4">
      <a href="#">
            <img class="img-fluid" src="<?php echo base_url()?>assets/img/resonador.jpg" alt="">
          </a>
    </div>

  </div>
  <!-- /.row -->

</div>
<!-- /.container -->